# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20161221_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storephoto',
            name='photos',
            field=models.URLField(),
        ),
    ]
